# Machine Learning / Aprendizagem Automática

## Sara C. Madeira, 2018/19

# ML Project  - Learning from Mental Health in Tech Surveys 

## Logistics

**Students are encouraged to work in teams of 4 people**. 

Projects with smaller teams are allowed, but will not have better grades for this reason. 

The quality of the project will dictate its grade, not the number of people working.

**The project's solution should be uploaded in Moodle before the end of January, 9th 2019 (last day before the exams season).** 

**Other deadline date might be considered provided the majority of the students agree with it.**

Students should **upload a `.zip` file** containing all the files necessary for project evaluation. 

**It is mandatory to produce a Jupyter notebook containing code and text/images/tables/etc describing the solution and the results.**

**Decisions should be fundamented and results should be critically discussed.**

## Tools

You should use [Python 3](https://www.python.org) and [Jupyter Notebook](http://jupyter.org), together with **[Scikit-learn](http://scikit-learn.org/stable/)**, **[Orange3](https://orange.biolab.si)**, or **both**.

**[Orange3](https://orange.biolab.si)** can be used through its **[programmatic version](https://docs.orange.biolab.si/3/data-mining-library/)**, by importing and using its packages, or throught its **workflow version**. 

If you use workflows you have to deliver the workflow files and explain the options taken in each widget in your notebook.

## Dataset

The dataset to be analysed is **`mental-heath-in-tech-2016.csv`**, made avaliable together with this project description. 

This dataset, downloaded from [Kaggle](https://www.kaggle.com), contains data from [OSMI Mental Health in Tech Survey](https://www.kaggle.com/osmi/mental-health-in-tech-survey), collected during a survey aiming at measuring **attitudes towards mental health and frequency of mental health disorders in the Tech workplace**, carried out in 2016.

The **1433 surveys/instances** are described by **63 categorical/numerical features**, where the following questions were asked:

* Q1 - "Are you self-employed?"
* Q2 - "How many employees does your company or organization have?"
* Q3 - "Is your employer primarily a tech company/organization?"
* Q4 - "Is your primary role within your company related to tech/IT?"
* Q5 - "Does your employer provide mental health benefits as part of healthcare coverage?"
* Q6 - "Do you know the options for mental health care available under your employer-provided coverage?"
* Q7 - "Has your employer ever formally discussed mental health (for example, as part of a wellness campaign or other official communication)?"
* Q8 - "Does your employer offer resources to learn more about mental health concerns and options for seeking help?"
* Q9 - "Is your anonymity protected if you choose to take advantage of mental health or substance abuse treatment resources provided by your employer?"
* Q10 - "If a mental health issue prompted you to request a medical leave from work, asking for that leave would be:..."
* Q11 - "Do you think that discussing a mental health disorder with your employer would have negative consequences?"
* Q12 - "Do you think that discussing a physical health issue with your employer would have negative consequences?"
* Q13 - "Would you feel comfortable discussing a mental health disorder with your coworkers?"
* Q14 - "Would you feel comfortable discussing a mental health disorder with your direct supervisor(s)?"
* Q15 - "Do you feel that your employer takes mental health as seriously as physical health?"
* Q16 - "Have you heard of or observed negative consequences for co-workers who have been open about mental health issues in your workplace?"
* Q17 - "Do you have medical coverage (private insurance or state-provided) which includes treatment of  mental health issues?"
* Q18 - "Do you know local or online resources to seek help for a mental health disorder?"
* Q19 - "If you have been diagnosed or treated for a mental health disorder, do you ever reveal this to clients or business contacts?"
* Q20 - "If you have revealed a mental health issue to a client or business contact, do you believe this has impacted you negatively?"
* Q21 - "If you have been diagnosed or treated for a mental health disorder, do you ever reveal this to coworkers or employees?"
* Q22 - "If you have revealed a mental health issue to a coworker or employee, do you believe this has impacted you negatively?"
* Q23 - "Do you believe your productivity is ever affected by a mental health issue?"
    * Q24 - "If yes, what percentage of your work time (time performing primary or secondary job functions) is affected by a mental health issue?"
* Q25 - "Do you have previous employers?"
* Q26 - "Have your previous employers provided mental health benefits?"
* Q27 - "Were you aware of the options for mental health care provided by your previous employers?"
* Q28 - "Did your previous employers ever formally discuss mental health (as part of a wellness campaign or other offi8cial communication)?"
* Q29 - "Did your previous employers provide resources to learn more about mental health issues and how to seek help?"
* Q30 - "Was your anonymity protected if you chose to take advantage of mental health or substance abuse treatment resources with previous employers?"
* Q31 - "Do you think that discussing a mental health disorder with previous employers would have negative consequences?"
* Q32 - "Do you think that discussing a physical health issue with previous employers would have negative consequences?"
* Q33 - "Would you have been willing to discuss a mental health issue with your previous co-workers?"
* Q34 - "Would you have been willing to discuss a mental health issue with your direct supervisor(s)?"
* Q35 - "Did you feel that your previous employers took mental health as seriously as physical health?"
* Q36 - "Did you hear of or observe negative consequences for co-workers with mental health issues in your previous workplaces?"
* Q37 - "Would you be willing to bring up a physical health issue with a potential employer in an interview?"
    * Q38 - "Why or why not?"
* Q39 - "Would you bring up a mental health issue with a potential employer in an interview?" 
    * Q40 - "Why or why not?"
* Q41 - "Do you feel that being identified as a person with a mental health issue would hurt your career?"
* Q42 - "Do you think that team members/co-workers would view you more negatively if they knew you suffered from a mental health issue?"
* Q43 - "How willing would you be to share with friends and family that you have a mental illness?"
* Q44 - "Have you observed or experienced an unsupportive or badly handled response to a mental health issue in your current or previous workplace?"
* Q45 - "Have your observations of how another individual who discussed a mental health disorder made you less likely to reveal a mental health issue yourself in your current workplace?"
* Q46 - "Do you have a family history of mental illness?"
* Q47 - "Have you had a mental health disorder in the past?"
* **Q48 - "Do you currently have a mental health disorder?"**
    * **Q49 - "If yes, what condition(s) have you been diagnosed with?"**
    * **Q50 - "If maybe, what condition(s) do you believe you have?"**
* Q51 - "Have you been diagnosed with a mental health condition by a medical professional?"
    * Q52 - "If so, what condition(s) were you diagnosed with?"
* Q53 - "Have you ever sought treatment for a mental health issue from a mental health professional?"
* Q54 - "If you have a mental health issue, do you feel that it interferes with your work when being treated effectively?"
* Q55 - "If you have a mental health issue, do you feel that it interferes with your work when NOT being treated effectively?"
* Q56 - "What is your age?"
* Q57 - "What is your gender?"
* Q58 - "What country do you live in?"
    * Q59 - "What US state or territory do you live in?"
* Q60 - "What country do you work in?"
    * Q61 - "What US state or territory do you work in?"
* Q62 - "Which of the following best describes your work position?"
* Q63 - "Do you work remotely?"

**IMPORTANT NOTES:**

   1. **Some questions might not be asked**. For example, Q49 and Q50 will only be asked if Q48 is "yes". 
   2. Data can contain **errors/typos**, whose correction might improve the analysis.
   3. Data can contain **missing values**, that you might decide to fill.
   4. **Not all features are necessarily important** for the analysis.
   5. Depending on the analysis, **some features might have to be excluded**. An example is when we want to predict a certain feature and there are other features that only have values for certain values of the target.

## Task 0 (Know your Data) - Preliminary Data Analysis

## 0.1. Loading Data

In [1]:
#importar os dados a partir do ficheiro csv
import numpy as np
import pandas as pd
dataset=pd.read_csv("mental-heath-in-tech-2016.csv")

In [2]:
#display do data frame
dataset

Are you self-employed?  \
0                          0   
1                          0   
2                          0   
3                          1   
4                          0   
5                          0   
6                          0   
7                          0   
8                          0   
9                          1   
10                         0   
11                         0   
12                         0   
13                         0   
14                         0   
15                         0   
16                         0   
17                         0   
18                         1   
19                         0   
20                         0   
21                         0   
22                         0   
23                         0   
24                         1   
25                         0   
26                         0   
27                         0   
28                         0   
29                         0   
...                      ...   
1403                       0   
1404                       1   
1405                       0   
1406                       0   
1407                       0   
1408                       1   
1409                       0   
1410                       0   
1411                       0   
1412                       0   
1413                       0   
1414                       0   
1415                       0   
1416                       0   
1417                       0   
1418                       0   
1419                       0   
1420                       1   
1421                       0   
1422                       0   
1423                       0   
1424                       0   
1425                       0   
1426                       0   
1427                       0   
1428                       1   
1429                       1   
1430                       0   
1431                       0   
1432                       0   

     How many employees does your company or organization have?  \
0                                                26-100           
1                                                  6-25           
2                                                  6-25           
3                                                   NaN           
4                                                  6-25           
5                                        More than 1000           
6                                                26-100           
7                                        More than 1000           
8                                                26-100           
9                                                   NaN           
10                                               26-100           
11                                              100-500           
12                                              100-500           
13                                              100-500           
14                                              100-500           
15                                              100-500           
16                                               26-100           
17                                             500-1000           
18                                                  NaN           
19                                              100-500           
20                                                 6-25           
21                                       More than 1000           
22                                               26-100           
23                                                  1-5           
24                                                  NaN           
25                                              100-500           
26                                               26-100           
27                                              100-500           
28                                             500-1000           
29         

## 0.2. Understanding Data

In this task you should understand better the features you have, the distribution of values, potential errors, etc and plan/describe what data preprocessing steps should be performed next.

...

In [3]:
#tamanho do data frame
dataset.size


90279

In [4]:
#número de colunas do data frame
len(dataset.columns)

63

In [5]:
#número de linhas do data frame
len(dataset)

1433

In [6]:
#forma do data frame (número de colunas e de linhas) - o que é confirmado pelas duas linhas de código anteriores
dataset.shape

(1433, 63)

In [7]:
#Vamos verificar quais as perguntas feitas no inquérito,ou seja, quais os títulos das colunas do dataframe
dataset.columns

Index(['Are you self-employed?',
       'How many employees does your company or organization have?',
       'Is your employer primarily a tech company/organization?',
       'Is your primary role within your company related to tech/IT?',
       'Does your employer provide mental health benefits as part of healthcare coverage?',
       'Do you know the options for mental health care available under your employer-provided coverage?',
       'Has your employer ever formally discussed mental health (for example, as part of a wellness campaign or other official communication)?',
       'Does your employer offer resources to learn more about mental health concerns and options for seeking help?',
       'Is your anonymity protected if you choose to take advantage of mental health or substance abuse treatment resources provided by your employer?',
       'If a mental health issue prompted you to request a medical leave from work, asking for that leave would be:',
       'Do you think that dis

In [8]:
#Experiências (para apagar no fim)

#dataset[dataset.columns[5]]

#dataset[dataset.columns[5]].isnull()

Seguidamente vamos ver quais as respostas dadas ao inquérito. Esta etapa é muito importante no tratamento de dados pois vai
permitir eliminar null values e respostas que claramente não foram dadas de forma séria, bem como uniformizar os dados obtidos.
Com um ciclo for vamos correr o dataset e, para cada questão expôr as respostas únicas

In [9]:
for i in range (len(dataset.columns)):
    print('Q'+str(i+1)+" - "+dataset.columns[i])
    print("Diferent answers: ")
    print(dataset[dataset.columns[i]].unique())
    print("Number of diferent answers: ")
    print(len(dataset[dataset.columns[i]].unique()))
    print()



Q1 - Are you self-employed?
Diferent answers: 
[0 1]
Number of diferent answers: 
2

Q2 - How many employees does your company or organization have?
Diferent answers: 
['26-100' '6-25' nan 'More than 1000' '100-500' '500-1000' '1-5']
Number of diferent answers: 
7

Q3 - Is your employer primarily a tech company/organization?
Diferent answers: 
[ 1. nan  0.]
Number of diferent answers: 
3

Q4 - Is your primary role within your company related to tech/IT?
Diferent answers: 
[nan  1.  0.]
Number of diferent answers: 
3

Q5 - Does your employer provide mental health benefits as part of healthcare coverage?
Diferent answers: 
['Not eligible for coverage / N/A' 'No' nan 'Yes' "I don't know"]
Number of diferent answers: 
5

Q6 - Do you know the options for mental health care available under your employer-provided coverage?
Diferent answers: 
[nan 'Yes' 'I am not sure' 'No']
Number of diferent answers: 
4

Q7 - Has your employer ever formally discussed mental health (for example, as part of a 

In [10]:
# Vamos verificar quantas colunas têm 'NaN'

cols_nan = 0

for i in range (63):
    if dataset[dataset.columns[i]].isnull().any():
        cols_nan+=1

cols_nan
        

44

Das 63 perguntas efectuadas, apenas 44 delas não têm valores em falta (NaN). Precisamos então de uma maneira de lidar com estes valores. 

In [11]:
#Vamos analisar melhor o número de respostas dadas, por cada pergunta:

for i in range (len(dataset.columns)):
    print('Q'+str(i+1))
    print(len(dataset[dataset.columns[i]].unique()))

Q1
2
Q2
7
Q3
3
Q4
3
Q5
5
Q6
4
Q7
4
Q8
4
Q9
4
Q10
7
Q11
4
Q12
4
Q13
4
Q14
4
Q15
4
Q16
3
Q17
3
Q18
4
Q19
6
Q20
4
Q21
6
Q22
5
Q23
5
Q24
5
Q25
2
Q26
5
Q27
5
Q28
5
Q29
4
Q30
5
Q31
5
Q32
4
Q33
4
Q34
5
Q35
5
Q36
4
Q37
3
Q38
1086
Q39
3
Q40
1081
Q41
5
Q42
5
Q43
6
Q44
5
Q45
4
Q46
3
Q47
3
Q48
3
Q49
129
Q50
100
Q51
2
Q52
117
Q53
2
Q54
5
Q55
5
Q56
53
Q57
71
Q58
53
Q59
48
Q60
53
Q61
49
Q62
264
Q63
3


É possível verificar que as perguntas n.ºs 37,39,48,49,51,55,56,57,58,59,60 e 61 são as que apresentam maior disparidade de respostas de entre os 1433 inquiridos.Vamos então ver que perguntas são essas:

In [12]:
l=[37,39,48,49,51,55,56,57,58,59,60,61]

for i in l:
    print('Q'+str(i+1)+" - "+dataset.columns[i])
    print(len(dataset[dataset.columns[i]].unique()))

Q38 - Why or why not?
1086
Q40 - Why or why not?.1
1081
Q49 - If yes, what condition(s) have you been diagnosed with?
129
Q50 - If maybe, what condition(s) do you believe you have?
100
Q52 - If so, what condition(s) were you diagnosed with?
117
Q56 - What is your age?
53
Q57 - What is your gender?
71
Q58 - What country do you live in?
53
Q59 - What US state or territory do you live in?
48
Q60 - What country do you work in?
53
Q61 - What US state or territory do you work in?
49
Q62 - Which of the following best describes your work position?
264


De entre estas doze perguntas há duas que poderão de imediato ser processadas: o género e a idade. Vamos tratar cada uma delas isoladamente  

In [13]:
#idade


print('Q'+str(55+1)+" - "+dataset.columns[55])
print("Diferent answers: ")
print(dataset[dataset.columns[55]].unique())
print("Number of diferent answers: ")
print(len(dataset[dataset.columns[55]].unique()))
print()


Q56 - What is your age?
Diferent answers: 
[ 39  29  38  43  42  30  37  44  28  34  35  52  32  25  31  26  33  27
  36  40  46  41  45  19  21  24  17  23  22  51  48  55  50  49  20  54
  47  56  57  63  99  61 323  62  53  58   3  66  59  15  65  74  70]
Number of diferent answers: 
53



Mas qual é a frequência de cada entrada?

In [14]:
dataset.groupby(dataset.columns[55]).size()

What is your age?
3       1
15      1
17      1
19      4
20      6
21     15
22     32
23     24
24     42
25     44
26     64
27     63
28     74
29     79
30     94
31     82
32     72
33     69
34     69
35     74
36     50
37     59
38     54
39     55
40     36
41     24
42     29
43     30
44     31
45     27
46     22
47     14
48      9
49     13
50      9
51      7
52      7
53      3
54      7
55     12
56      5
57      4
58      1
59      2
61      2
62      1
63      4
65      1
66      1
70      1
74      1
99      1
323     1
dtype: int64

É possível observar que existem dois valores que apenas têm a frequência de um e que são impossíveis de corresponder à idade: '323' e '3'. Muito provavelmente a entrada '99' anos também será falsa por isso será igualmente removida. Contudo os dois primeiros valores têm de ser substituidos.

In [15]:
dataset.replace({dataset.columns[55]: [323,99,3]},np.NaN, inplace=True)

In [16]:

print('Q'+str(55+1)+" - "+dataset.columns[55])
print("Diferent answers: ")
print(dataset[dataset.columns[55]].unique())
print("Number of diferent answers: ")
print(len(dataset[dataset.columns[55]].unique()))
print()

Q56 - What is your age?
Diferent answers: 
[39. 29. 38. 43. 42. 30. 37. 44. 28. 34. 35. 52. 32. 25. 31. 26. 33. 27.
 36. 40. 46. 41. 45. 19. 21. 24. 17. 23. 22. 51. 48. 55. 50. 49. 20. 54.
 47. 56. 57. 63. nan 61. 62. 53. 58. 66. 59. 15. 65. 74. 70.]
Number of diferent answers: 
51



A idade de cada inquirido, sendo uma variável numérica foi convertida em categórica, dentro de 4 categorias: "M30", "30_40", "40_50" and "P50".

In [17]:
"""Sendo que agora temos 3 NaN ali no meio não seria conveniente antes de categorizar 
a variável preencher os NaN em valta com o ffill ou bfill?"""

'Sendo que agora temos 3 NaN ali no meio não seria conveniente antes de categorizar \na variável preencher os NaN em valta com o ffill ou bfill?'

In [18]:
#Fazer as listas para posterior substituição pela classe categórica:

l_M30=[]
l_30_40=[]
l_40_50=[]
l_P50=[]

for i in dataset[dataset.columns[55]]:
    if i<30:
        l_M30.append(i)
    if i>=30 and i<40:
        l_30_40.append(i)
    if i>=40 and i<50:
        l_40_50.append(i)
    if i>=50:
        l_P50.append(i)
    

In [19]:
#Testes

print(len(l_M30),len(l_30_40),len(l_40_50),len(l_P50),len(l_M30)+len(l_30_40)+len(l_40_50)+len(l_P50))

449 678 235 68 1430


Vamos agora tratar de substituir os valores numéricos pelo seu grupo correspondente:

In [20]:
dataset.replace({dataset.columns[55]: l_M30},'M30', inplace=True)

In [21]:
dataset.replace({dataset.columns[55]: l_30_40},'30_40', inplace=True)

In [22]:
dataset.replace({dataset.columns[55]: l_40_50},'40_50', inplace=True)

In [23]:
dataset.replace({dataset.columns[55]: l_P50},'P50', inplace=True)

In [24]:
print('Q'+str(55+1)+" - "+dataset.columns[55])
print("Diferent answers: ")
print(dataset[dataset.columns[55]].unique())
print("Number of diferent answers: ")
print(len(dataset[dataset.columns[55]].unique()))
print()

Q56 - What is your age?
Diferent answers: 
['30_40' 'M30' '40_50' 'P50' nan]
Number of diferent answers: 
5



In [25]:
dataset.groupby(dataset.columns[55]).size()

What is your age?
30_40    678
40_50    235
M30      449
P50       68
dtype: int64

Vamos agora lidar com o género dos inquiridos:

In [26]:
#Respostas distintas:

print('Q'+str(56+1)+" - "+dataset.columns[56])
print("Diferent answers: ")
print(dataset[dataset.columns[56]].unique())
print("Number of diferent answers: ")
print(len(dataset[dataset.columns[56]].unique()))
print()

Q57 - What is your gender?
Diferent answers: 
['Male' 'male' 'Male ' 'Female' 'M' 'female' 'm' 'I identify as female.'
 'female ' 'Bigender' 'non-binary' 'Female assigned at birth ' 'F' 'Woman'
 'man' 'fm' 'f' 'Cis female ' 'Transitioned, M2F'
 'Genderfluid (born female)' 'Other/Transfeminine'
 'Female or Multi-Gender Femme' 'Female ' 'woman' 'female/woman'
 'Cis male' 'Male.' 'Androgynous' 'male 9:1 female, roughly' nan
 'Male (cis)' 'Other' 'nb masculine' 'Cisgender Female' 'Man'
 'Sex is male' 'none of your business' 'genderqueer' 'cis male' 'Human'
 'Genderfluid' 'Enby' 'Malr' 'genderqueer woman' 'mtf' 'Queer' 'Agender'
 'Dude' 'Fluid'
 "I'm a man why didn't you make this a drop down question. You should of asked sex? And I would of answered yes please. Seriously how much text can this take? "
 'mail' 'M|' 'Male/genderqueer' 'fem' 'Nonbinary' 'male ' 'human'
 'Female (props for making this a freeform field, though)' ' Female'
 'Unicorn' 'Cis Male' 'Male (trans, FtM)' 'Cis-woman' 'G

In [27]:
#substituição dos masculinos
dataset.replace({dataset.columns[56]: ['male','cisdude','Cis Male','Sex is male',"I'm a man why didn't you make this a drop down question. You should of asked sex? And I would of answered yes please. Seriously how much text can this take? ",
 'mail','M|','Male ','Dude','Malr','M','male ','cis male','MALE','m','man','Cis male','cis man','Male.','Male (cis)','Man']},'Male', inplace=True)

In [28]:
#substituição dos femininos
dataset.replace({dataset.columns[56]: ['Cis Female','Female assigned at birth ','fem','Cis-woman','f','Cis female ','Female (props for making this a freeform field, though)','female','I identify as female.','female ','Female ','woman','female/woman',' Female','Cisgender Female', 'cis-woman', 'F', 'Female', 'Woman']},'Female', inplace=True)

In [29]:
#substituição dos outros
dataset.replace({dataset.columns[56]: ['Bigender','Unicorn','non-binary','fm','Transitioned, M2F','Genderfluid (born female)','Other/Transfeminine','Female or Multi-Gender Femme','Androgynous','male 9:1 female, roughly','Other','nb masculine','none of your business','genderqueer','Human','Genderfluid','Enby','genderqueer woman','mtf','Queer','Agender','Fluid','Male/genderqueer','Nonbinary','human','Male (trans, FtM)','Genderqueer','Genderflux demi-girl','female-bodied; no feelings about gender','AFAB','Transgender woman']},'Other', inplace=True)

In [30]:
print('Q'+str(56+1)+" - "+dataset.columns[56])
print("Diferent answers: ")
print(dataset[dataset.columns[56]].unique())
print("Number of diferent answers: ")
print(len(dataset[dataset.columns[56]].unique()))
print()

Q57 - What is your gender?
Diferent answers: 
['Male' 'Female' 'Other' nan]
Number of diferent answers: 
4



In [31]:
#Ver a distribuição do inquérito,por sexo

dataset.groupby(dataset.columns[56]).size()

What is your gender?
Female     337
Male      1057
Other       36
dtype: int64

In [32]:
#Novo comprimento do dataset

len(dataset[dataset.columns[56]])

1433

Tratar das condições psicológicas:

In [33]:
#Respostas distintas:

print('Q'+str(48+1)+" - "+dataset.columns[48])
print("Diferent answers: ")
print(dataset[dataset.columns[48]].unique())
print("Number of diferent answers: ")
print(len(dataset[dataset.columns[48]].unique()))
print()

Q49 - If yes, what condition(s) have you been diagnosed with?
Diferent answers: 
[nan
 'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)'
 'Anxiety Disorder (Generalized, Social, Phobia, etc)|Stress Response Syndromes'
 'Anxiety Disorder (Generalized, Social, Phobia, etc)|Stress Response Syndromes|Substance Use Disorder'
 'Anxiety Disorder (Generalized, Social, Phobia, etc)|Substance Use Disorder'
 'Mood Disorder (Depression, Bipolar Disorder, etc)'
 'Anxiety Disorder (Generalized, Social, Phobia, etc)'
 'Anxiety Disorder (Generalized, Social, Phobia, etc)|Obsessive-Compulsive Disorder'
 'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Eating Disorder (Anorexia, Bulimia, etc)|Obsessive-Compulsive Disorder'
 'Personality Disorder (Borderline, Antisocial, Paranoid, etc)|Attention Deficit Hyperactivity Disorder'
 'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Dep

In [34]:
#Dicionário com as condições psicológicas e o grupo onde vão ficar

dic = {'Anxiety Disorder': 'q49_Anxiety Disorder','Mood Disorder':'q49_Mood Disorder', 'Eating Disorder':'q49_Eating Disorder','Stress Response Syndromes':'q49_Stress Response Syndromes','Substance Use Disorder':'q49_Substance Use Disorder',
'Obsessive-Compulsive Disorder':'q49_Obsessive-Compulsive Disorder','Addictive Disorder':'q49_Addictive Disorder','Post-traumatic Stress Disorder':'q49_Post-traumatic Stress Disorder','Dissociative Disorder':'q49_Dissociative Disorder',
'Autism/Asperger’s':'q49_Autism/Asperger’s','Personality Disorder':'q49_Personality Disorder','Attention Deficit Hyperactivity Disorder':'q49_Attention Deficit Hyperactivity Disorder','Psychotic Disorder (Schizophrenia, Schizoaffective, etc)':'q49_Psychotic Disorder (Schizophrenia, Schizoaffective, etc)',
'Autism Spectrum Disorder':'q49_Autism/Asperger’s',"Autism (Asperger's)":'q49_Autism/Asperger’s'}

In [35]:
#ciclo para associar as condições psicológicas aos seus novos grupos

for i in range(len(dataset[dataset.columns[48]])):
    for j in dic.keys():
        if j in str(dataset[dataset.columns[48]][i]):
            dataset.replace(dataset[dataset.columns[48]][i],dic[j],inplace=True)

In [36]:
#Replace para as Other Disorders
dataset.replace({dataset.columns[48]: ['Seasonal Affective Disorder','Burn out','PDD-NOS','Depression','Traumatic Brain Injury','Sexual addiction','Combination of physical impairment (strongly near-sighted) with a possibly mental one (MCD / "ADHD", though its actually a stimulus filtering impairment)',
"I haven't been formally diagnosed, so I felt uncomfortable answering, but Social Anxiety and Depression."]},'q49_Other Disorders', inplace=True)

In [37]:
#Respostas distintas:

print('Q'+str(48+1)+" - "+dataset.columns[48])
print("Diferent answers: ")
print(dataset[dataset.columns[48]].unique())
print("Number of diferent answers: ")
print(len(dataset[dataset.columns[48]].unique()))
print()

Q49 - If yes, what condition(s) have you been diagnosed with?
Diferent answers: 
[nan 'q49_Anxiety Disorder' 'q49_Mood Disorder' 'q49_Personality Disorder'
 'q49_Attention Deficit Hyperactivity Disorder' 'q49_Other Disorders'
 'q49_Post-traumatic Stress Disorder' 'q49_Stress Response Syndromes'
 'q49_Autism/Asperger’s' 'q49_Addictive Disorder'
 'q49_Obsessive-Compulsive Disorder'
 'q49_Psychotic Disorder (Schizophrenia, Schizoaffective, etc)'
 'q49_Substance Use Disorder' 'q49_Eating Disorder']
Number of diferent answers: 
14



Tratar das profissões:

In [38]:
#Respostas distintas:

print('Q'+str(61+1)+" - "+dataset.columns[61])
print("Diferent answers: ")
print(dataset[dataset.columns[61]].unique())
print("Number of diferent answers: ")
print(len(dataset[dataset.columns[61]].unique()))
print()

Q62 - Which of the following best describes your work position?
Diferent answers: 
['Back-end Developer' 'Back-end Developer|Front-end Developer'
 'Supervisor/Team Lead'
 'Executive Leadership|Supervisor/Team Lead|Dev Evangelist/Advocate|DevOps/SysAdmin|Support|Back-end Developer|Front-end Developer'
 'DevOps/SysAdmin|Support|Back-end Developer|Front-end Developer|Designer'
 'Dev Evangelist/Advocate|Back-end Developer'
 'Support|Back-end Developer|One-person shop'
 'One-person shop|Front-end Developer|Back-end Developer'
 'Front-end Developer' 'Executive Leadership'
 'Supervisor/Team Lead|Dev Evangelist/Advocate|Back-end Developer|Front-end Developer'
 'DevOps/SysAdmin|Back-end Developer|Front-end Developer' 'Designer'
 'Other|Executive Leadership' 'One-person shop' 'Other'
 'Supervisor/Team Lead|Support|Back-end Developer'
 'Supervisor/Team Lead|DevOps/SysAdmin|Back-end Developer'
 'Other|Supervisor/Team Lead|Support|Back-end Developer|Designer'
 'Supervisor/Team Lead|Back-end Develop

In [39]:
dic2 = {'Front-end Developer':'q62_Front-end Developer','Designer':'q62_Designer','Executive Leadership':'q62_Executive Leadership','One-person shop':'q62_One-person shop','Back-end Developer':'q62_Back-end Developer',
'Supervisor/Team Lead':'q62_Supervisor/Team Lead','Dev Evangelist/Advocate':'q62_Dev Evangelist/Advocate','DevOps/SysAdmin':'q62_DevOps/SysAdmin','Sales':'q62_Sales','Support':'q62_Support','HR':'q62_HR'}

In [40]:
dic2.keys()

dict_keys(['Front-end Developer', 'Designer', 'Executive Leadership', 'One-person shop', 'Back-end Developer', 'Supervisor/Team Lead', 'Dev Evangelist/Advocate', 'DevOps/SysAdmin', 'Sales', 'Support', 'HR'])

In [41]:
#ciclo para associar as profissões aos seus novos grupos

for i in range(len(dataset[dataset.columns[61]])):
    for j in dic2.keys():
        if j in str(dataset[dataset.columns[61]][i]):
            dataset.replace(dataset[dataset.columns[61]][i],dic2[j],inplace=True)

In [42]:
dataset.replace({dataset.columns[61]: ['Other']},'q62_Other', inplace=True)

In [43]:
#Respostas distintas:

print('Q'+str(61+1)+" - "+dataset.columns[61])
print("Diferent answers: ")
print(dataset[dataset.columns[61]].unique())
print("Number of diferent answers: ")
print(len(dataset[dataset.columns[61]].unique()))
print()

Q62 - Which of the following best describes your work position?
Diferent answers: 
['q62_Back-end Developer' 'q62_Front-end Developer'
 'q62_Supervisor/Team Lead' 'q62_One-person shop'
 'q62_Executive Leadership' 'q62_Designer' 'q62_Other' 'q62_Support'
 'q62_DevOps/SysAdmin' 'q62_Dev Evangelist/Advocate' 'q62_HR' 'q62_Sales']
Number of diferent answers: 
12



In [44]:
#retirar as linhas que têm NaN no género
dataset.dropna(axis=0, subset=[dataset.columns[56]], inplace=True)

In [45]:
#retirar as linhas que têm NaN na idade
dataset.dropna(axis=0, subset=[dataset.columns[55]], inplace=True)

In [46]:
len(dataset[dataset.columns[55]])

1427

## Task 1 (Supervised Learning) - Predicting if a person has a mental health disorder 

In this task you should **learn classifiers to predict if a person currently has a mental health disorder**:

* Choose one classifier in each category: Tree models, Rule models, Linear models, Distance-based models, and Probabilistic models.
* Use a train/test scheme or cross-validation.
* Describe the parameters used.
* Evaluate the results using an evaluation measure and confusion matrices.
* Choose the best classifier and fundament you choice.

## 1.1. Preprocessing Data for Classification

In [47]:
#Modelos a fazer:

#Tree models

#Rule models

## 1.2. Learning Classifiers

...

   ## 1.2.1 Tree models

In [48]:
#Tree models

Um dos pontos fortes das árvores de decisão é a possibilidade de trabalhar simultaneamente com valores numéricos e categóricos no mesmo dataset.

In [49]:
#Colunas com menos de 75% de NaN

new_cols=dataset.loc[:,dataset.isnull().sum()<0.75*dataset.shape[0]].columns

In [50]:
len(new_cols)

53

In [51]:
#colocar numa lista à parte o nome das colunas que indicam se o paciente tem uma doença mental
#Descrever o motivo porque estas colunas foram removidas

remove_list=[18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,37,39,42,48,49,50,51,53,54,58,60]

remove_list_name=[]

for i in remove_list:
    remove_list_name.append((dataset.columns[i]))
    
len(remove_list_name)

29

In [52]:
new_cols2=[]

for i in new_cols:
    if i not in remove_list_name:
        new_cols2.append(i)
        
len(new_cols2)

31

In [53]:
#retirar a coluna 'Do you currently have a mental health disorder?' da lista de colunas      
new_cols2.remove('Do you currently have a mental health disorder?')

In [54]:
len(new_cols2)

30

In [55]:
#e voltar a adicioná-la, para que fique em último lugar
new_cols2.append('Do you currently have a mental health disorder?')
new_cols2

['Are you self-employed?',
 'How many employees does your company or organization have?',
 'Is your employer primarily a tech company/organization?',
 'Does your employer provide mental health benefits as part of healthcare coverage?',
 'Do you know the options for mental health care available under your employer-provided coverage?',
 'Has your employer ever formally discussed mental health (for example, as part of a wellness campaign or other official communication)?',
 'Does your employer offer resources to learn more about mental health concerns and options for seeking help?',
 'Is your anonymity protected if you choose to take advantage of mental health or substance abuse treatment resources provided by your employer?',
 'If a mental health issue prompted you to request a medical leave from work, asking for that leave would be:',
 'Do you think that discussing a mental health disorder with your employer would have negative consequences?',
 'Do you think that discussing a physical h

In [56]:
len(new_cols2)

31

In [57]:
#Fazer o novo dataset

my_df_new=dataset[new_cols2]

In [58]:
len(dataset.columns)

63

In [59]:
len(my_df_new.columns)

31

In [60]:
#Verificar a percentagem de NaN por questão

print(str((my_df_new.isna().sum())/len(my_df_new[my_df_new.columns])))

Are you self-employed?                                                                                                                                                              0.000000
How many employees does your company or organization have?                                                                                                                          0.201121
Is your employer primarily a tech company/organization?                                                                                                                             0.201121
Does your employer provide mental health benefits as part of healthcare coverage?                                                                                                   0.201121
Do you know the options for mental health care available under your employer-provided coverage?                                                                                     0.293623
Has your employer ever formally discussed mental health

Vamos agora lidar com os missing values (NaN)

In [61]:
#Ver a moda de cada questão, uma vez que se tratam de valores discretos. O objetivo é substituir os NaN de cada coluna pela moda

import statistics

for i in range(len(my_df_new.columns)):
    print(my_df_new.columns[i])
    print(statistics.mode(my_df_new[my_df_new.columns[i]]))

Are you self-employed?
0
How many employees does your company or organization have?
26-100
Is your employer primarily a tech company/organization?
1.0
Does your employer provide mental health benefits as part of healthcare coverage?
Yes
Do you know the options for mental health care available under your employer-provided coverage?
nan
Has your employer ever formally discussed mental health (for example, as part of a wellness campaign or other official communication)?
No
Does your employer offer resources to learn more about mental health concerns and options for seeking help?
No
Is your anonymity protected if you choose to take advantage of mental health or substance abuse treatment resources provided by your employer?
I don't know
If a mental health issue prompted you to request a medical leave from work, asking for that leave would be:
nan
Do you think that discussing a mental health disorder with your employer would have negative consequences?
Maybe
Do you think that discussing a ph

In [62]:
#Ver as perguntas cuja moda é NaN:

nan_list=[]

for i in range(len(my_df_new.columns)):
    if str(statistics.mode(my_df_new[my_df_new.columns[i]]))=='nan':
        nan_list.append(my_df_new.columns[i])
        
        
nan_list       

['Do you know the options for mental health care available under your employer-provided coverage?',
 'If a mental health issue prompted you to request a medical leave from work, asking for that leave would be:',
 'Have your observations of how another individual who discussed a mental health disorder made you less likely to reveal a mental health issue yourself in your current workplace?']

In [63]:
#Ver a distrubuição das respostas, para posteriormente substituir os NaN destas perguntas pela segunda resposta mais frequente

for i in nan_list:
    print(my_df_new.groupby(i).size())

Do you know the options for mental health care available under your employer-provided coverage?
I am not sure    351
No               350
Yes              307
dtype: int64
If a mental health issue prompted you to request a medical leave from work, asking for that leave would be:
I don't know                  148
Neither easy nor difficult    178
Somewhat difficult            199
Somewhat easy                 277
Very difficult                118
Very easy                     220
dtype: int64
Have your observations of how another individual who discussed a mental health disorder made you less likely to reveal a mental health issue yourself in your current workplace?
Maybe    176
No       233
Yes      243
dtype: int64


In [64]:
#Substituir os NaN da cada coluna pelo valor mais comum de cada coluna (moda)

for i in range(len(my_df_new.columns)):
    my_df_new[my_df_new.columns[i]].fillna(statistics.mode(my_df_new[my_df_new.columns[i]]),inplace=True)

/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py:5430: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)


In [65]:
#E como se pode verificar já só há três colunas com NaN, que são aquelas cuja moda é NaN. Nestas três colunas
#os valores de NaN serão substituidos pelo segundo valor mais comum

print(str((my_df_new.isna().sum())/len(my_df_new[my_df_new.columns])))

Are you self-employed?                                                                                                                                                              0.000000
How many employees does your company or organization have?                                                                                                                          0.000000
Is your employer primarily a tech company/organization?                                                                                                                             0.000000
Does your employer provide mental health benefits as part of healthcare coverage?                                                                                                   0.000000
Do you know the options for mental health care available under your employer-provided coverage?                                                                                     0.293623
Has your employer ever formally discussed mental health

In [66]:
#Substituição dos valores de NaN das colunas cuja moda era NaN pelo segundo valor mais popular

my_df_new[nan_list[0]].fillna('I am not sure',inplace=True)

my_df_new[nan_list[1]].fillna('Somewhat easy',inplace=True)

my_df_new[nan_list[2]].fillna('Yes',inplace=True)

/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py:5430: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)


In [67]:
#E como se pode verificar já não existem NaN no dataset 

print(str((my_df_new.isna().sum())/len(my_df_new[my_df_new.columns])))

Are you self-employed?                                                                                                                                                              0.0
How many employees does your company or organization have?                                                                                                                          0.0
Is your employer primarily a tech company/organization?                                                                                                                             0.0
Does your employer provide mental health benefits as part of healthcare coverage?                                                                                                   0.0
Do you know the options for mental health care available under your employer-provided coverage?                                                                                     0.0
Has your employer ever formally discussed mental health (for example, as part of

In [68]:
def load_data(dataset_name):
    """Através do nome do dataset a função vai definir a table_X, a table_y, as features e o target"""
    df = dataset_name
    nc = df.shape[1] # number of columns
    matrix = df.as_matrix() # Convert dataframe to darray
    table_X = matrix [:, 0:nc-1] # get features 
    table_y = matrix [:, nc-1] # get class (last columns)           
    features = df.columns.values[0:nc-1] #get features names
    target = df.columns.values[nc-1] #get target name
    return table_X, table_y, features, target

table_X, table_y, features, target = load_data(my_df_new)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:5: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """


In [69]:
features

array(['Are you self-employed?',
       'How many employees does your company or organization have?',
       'Is your employer primarily a tech company/organization?',
       'Does your employer provide mental health benefits as part of healthcare coverage?',
       'Do you know the options for mental health care available under your employer-provided coverage?',
       'Has your employer ever formally discussed mental health (for example, as part of a wellness campaign or other official communication)?',
       'Does your employer offer resources to learn more about mental health concerns and options for seeking help?',
       'Is your anonymity protected if you choose to take advantage of mental health or substance abuse treatment resources provided by your employer?',
       'If a mental health issue prompted you to request a medical leave from work, asking for that leave would be:',
       'Do you think that discussing a mental health disorder with your employer would have negative

In [70]:
table_X

array([[0, '26-100', 1.0, ..., 'United Kingdom',
        'q62_Back-end Developer', 'Sometimes'],
       [0, '6-25', 1.0, ..., 'United States of America',
        'q62_Front-end Developer', 'Never'],
       [0, '6-25', 1.0, ..., 'United Kingdom', 'q62_Back-end Developer',
        'Always'],
       ...,
       [0, '100-500', 1.0, ..., 'United States of America',
        'q62_Back-end Developer', 'Sometimes'],
       [0, '100-500', 0.0, ..., 'United States of America',
        'q62_DevOps/SysAdmin', 'Sometimes'],
       [0, '100-500', 1.0, ..., 'Canada', 'q62_Other', 'Sometimes']],
      dtype=object)

In [71]:
target

'Do you currently have a mental health disorder?'

In [72]:
table_y

array(['No', 'Yes', 'No', ..., 'Maybe', 'Yes', 'Yes'], dtype=object)

We start by defining the function ohenc_encode_feature that given a target column (col), the number of rows (nrow) and the number of possible values (ndim), replaces the original column by ndim new binary colums.

In [73]:
from sklearn.preprocessing import OneHotEncoder

def ohenc_encode_feature(table_X, col, nrow, ndim):
    enc = LabelEncoder()
    label_encoder = enc.fit(table_X[:, col])
    integer_classes = label_encoder.transform(label_encoder.classes_).reshape(ndim, 1)
    enc = OneHotEncoder()
    one_hot_encoder = enc.fit(integer_classes)
    # First, convert feature values to 0-(N-1) integers using label_encoder
    num_of_rows = nrow
    t = label_encoder.transform(table_X[:, col]).reshape(num_of_rows, 1)
    # Second, create a sparse matrix with col columns, each one indicating
    # whether the instance belongs to the class
    new_features = one_hot_encoder.transform(t)
    # Add the new features to table_X
    table_X = np.concatenate([table_X, new_features.toarray()], axis = 1)
    # Eliminate converted columns
    table_X = np.delete(table_X, [col], 1)
    return table_X

We still need the functions int_encode_feature and int_encode_class, since we have two features with two values ('Sex' and 'HasChildren'), and need to encode the target.

In [74]:
from sklearn.preprocessing import LabelEncoder

def int_encode_class(vect):
    enc = LabelEncoder()
    label_encoder = enc.fit(vect)
    integer_classes = label_encoder.transform(label_encoder.classes_)
    t = label_encoder.transform(vect)
    return t
    
def int_encode_feature(vect):
    return int_encode_class(vect)

Depois do dataframe estar devidamente processado é necessários transformar os valores categóricos em binários. Para isso será utilizado o one hot encoder. As colunas que têm mais do que dois valores categóricos como respostas ao inquérito ficarão com tantas colunas quantos forem esses valores categóricos. E cada uma dessas colunas terá um nome, associado à "coluna-mãe" que lhe deu origem. O seguinte código vai gerar os nomes das futuras colunas binárias dentro da lista 'features': 

In [75]:
#Testes

#len(my_df_new[my_df_new.columns[3]])
#table_X[:,2]

In [76]:
# columns with 2 categories or less are treated first
nrows=table_X.shape[0]

for i in range(len(my_df_new.columns)):
    ndim=len(my_df_new[my_df_new.columns[i]].unique()) # the number different categories in column i
    if ndim==2:
        table_X[:,i] = int_encode_feature(table_X[:,i]) 


In [77]:
type(features)

numpy.ndarray

In [78]:
# we encode now columns with more than 2 categories
# don't forget that when a column is encoded, it expands into (number of categories) columns that are added 
# at the end of the table; 
# cols_exp will store the number of columns with more than 2 categories already encoded

nrows=table_X.shape[0]
cols_exp=0
for i in range(len(my_df_new.columns)):
    ndim=len(np.unique(table_X[:,i-cols_exp]))
    if (ndim>2):
        table_X[:,i-cols_exp] = int_encode_feature(table_X[:, i-cols_exp])
        table_X=ohenc_encode_feature(table_X, i-cols_exp, nrows, ndim )
        features=np.delete(features,np.where(features==str(my_df_new.columns[i]))) #remove from array features the name of the column 
                                                       #that's going to be expanded
        cols_exp+=1
        for j in range(ndim):
            features=np.append(features,str(my_df_new.columns[i])+'_'+str(my_df_new[my_df_new.columns[i]].unique()[j]))
table_X       

array([[0, 1, 0, ..., 0.0, 0.0, 1.0],
       [0, 1, 0, ..., 0.0, 1.0, 0.0],
       [0, 1, 0, ..., 1.0, 0.0, 0.0],
       ...,
       [0, 1, 1, ..., 0.0, 0.0, 1.0],
       [0, 0, 0, ..., 0.0, 0.0, 1.0],
       [0, 1, 0, ..., 0.0, 0.0, 1.0]], dtype=object)

In [79]:
features

array(['Are you self-employed?',
       'Is your employer primarily a tech company/organization?',
       'Have you heard of or observed negative consequences for co-workers who have been open about mental health issues in your workplace?',
       'Have you ever sought treatment for a mental health issue from a mental health professional?',
       'How many employees does your company or organization have?_26-100',
       'How many employees does your company or organization have?_6-25',
       'How many employees does your company or organization have?_More than 1000',
       'How many employees does your company or organization have?_100-500',
       'How many employees does your company or organization have?_500-1000',
       'How many employees does your company or organization have?_1-5',
       'Does your employer provide mental health benefits as part of healthcare coverage?_Not eligible for coverage / N/A',
       'Does your employer provide mental health benefits as part of he

In [80]:
len(features)

204

In [81]:
#num_of_rows = table_X.shape[1]
table_X.shape

(1427, 204)

In [82]:
for i in range (len(my_df_new.columns)):
    print(my_df_new.columns[i])
    print("Diferent answers: ")
    print(my_df_new[my_df_new.columns[i]].unique())
    print("Number of diferent answers: ")
    print(len(my_df_new[my_df_new.columns[i]].unique()))
    print()


Are you self-employed?
Diferent answers: 
[0 1]
Number of diferent answers: 
2

How many employees does your company or organization have?
Diferent answers: 
['26-100' '6-25' 'More than 1000' '100-500' '500-1000' '1-5']
Number of diferent answers: 
6

Is your employer primarily a tech company/organization?
Diferent answers: 
[1. 0.]
Number of diferent answers: 
2

Does your employer provide mental health benefits as part of healthcare coverage?
Diferent answers: 
['Not eligible for coverage / N/A' 'No' 'Yes' "I don't know"]
Number of diferent answers: 
4

Do you know the options for mental health care available under your employer-provided coverage?
Diferent answers: 
['I am not sure' 'Yes' 'No']
Number of diferent answers: 
3

Has your employer ever formally discussed mental health (for example, as part of a wellness campaign or other official communication)?
Diferent answers: 
['No' 'Yes' "I don't know"]
Number of diferent answers: 
3

Does your employer offer resources to learn more

In [83]:
# Convert table_X to numerical values
table_X = table_X.astype(float)
table_X

array([[0., 1., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 1., 0., 0.],
       ...,
       [0., 1., 1., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 0., 1.]])

In [84]:
# ENCODE table_y (CLASS) with integers
table_y = int_encode_class(table_y)

# Convert table_y to numerical values
table_y = table_y.astype(float)
table_y

array([1., 2., 1., ..., 0., 2., 2.])

Learning the decision tree

In [85]:
# Learn the decision tree

from sklearn import tree

cdt = tree.DecisionTreeClassifier(criterion='gini')
cdt = cdt.fit(table_X, table_y)
cdt

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [86]:
# Visualize the decision tree

tree.export_graphviz(cdt, out_file='votingIssue.dot',
                     feature_names=features,
                     filled=True, rounded=True,
                     special_characters=True)

from subprocess import call
call(['dot', '-T', 'png', 'votingIssue.dot', '-o', 'votingIssue.png'])

FileNotFoundError: [Errno 2] No such file or directory: 'dot': 'dot'

***Nota: apagar isto***

Tenho de tratar os dados para se saber quais são os que têm valores binários e quais os que têm mais do que isso.
Talvez a melhor forma seja fazer um ciclo para ver quais as questões que têm valores binários e pôr essas numa lista.
Depois fazer outro ciclo para fazer o one hot encoder para as de valores binários. A seguir fazer mais um ciclo para as outras features que não sejam binárias

## 1.2.2 Rule models

In [ ]:
#Rule models

## 1.3. Classification - Results and Discussion 

...

   ## 1.2.1 Tree models

   ## 1.2.1 Rule models

## Task 2 (Unsupervised Learning) - Charactering people with mental health disorders

In this task you should **use unsupervised learning algorithms and try to characterize people with mental health disorders**:
* Use association rule mining to find **associations between features and mental health disorders**.
* Use **clustering algorithms to find groups describing similar people**, for example, is it possible to find groups of people with the same/similar mental health disorders.
* **Be creative and define your own unsupervised analysis!** What would it be interesting to find out ?

## 2.1. Preprocessing Data for Association Rule Mining

...

## 2.2. Finding Associations

...

## 2.3 Association Rules - Results and Discussion 

...

## 2.4. Preprocess Data for Clustering

...

## 2.5. Finding Groups

...

## 2.6. Clustering - Results and Discussion 

...

## 3. Final Comments and Conclusions

...